Id 4.3
TikhonovNikita1996/PetFamilyProject pull request #7
Opened 2024-11-13 11:09 UTC by TikhonovNikita1996

2024-11-13 13:37 UTC, KirillSachkov approved these changes

2024-11-13 13:37 UTC, KirillSachkov commented on Backend/src/PetFamily.Domain/Entities/Pet/Pet.cs
> +    {
Здесь должна быть валидация всех полей

2024-11-13 13:37 UTC, KirillSachkov commented on Backend/src/PetFamily.Domain/Entities/Volunteer/Volunteer.cs
> +        var volunteer = new Volunteer(id, fullname, age, email, gender, workingExperience, description,
Здесь должна быть валидация всех полей

2024-11-13 13:38 UTC, KirillSachkov requested changes
В ревью должны быть комментарии

2024-11-13 18:13 UTC, TikhonovNikita1996 commented on Backend/src/PetFamily.Domain/Entities/Pet/Pet.cs
> +    {
Добавил

2024-11-14 08:02 UTC, KirillSachkov requested changes

2024-11-14 08:02 UTC, KirillSachkov commented on Backend/src/PetFamily.Domain/Entities/Pet/Pet.cs
> +        if (weight == 0)
Здесь нужно проверять что > 0, негативным же не может быть значение

2024-11-14 08:02 UTC, KirillSachkov commented on Backend/src/PetFamily.Domain/Entities/Pet/Pet.cs
> +        if (string.IsNullOrWhiteSpace(petsName))
я бы сделал общий класс с константами и положил бы туда значения длины полей, например минимальную, среднюю и макс, и использовал бы тут для проверки длины полей, чтобы не было полей с 10000000 символами

2024-11-14 08:02 UTC, KirillSachkov commented on Backend/src/PetFamily.Domain/Entities/Pet/Species.cs
> +    public List<Breed> Breeds { get; set; }
коллекци должна быть IReadOnlyList, чтобы нельзя было извне её редактировать

2024-11-14 08:02 UTC, KirillSachkov commented on Backend/src/PetFamily.Domain/Entities/Volunteer/Volunteer.cs
> +        if (age == 0)
негативное значение возраста здесь пройдёт

2024-11-14 08:02 UTC, KirillSachkov commented on Backend/src/PetFamily.Domain/Entities/Volunteer/Volunteer.cs
> +        if (age == 0)
похожие случаи тоже нужно испарвить

2024-11-14 08:09 UTC, TikhonovNikita1996 commented on Backend/src/PetFamily.Domain/Entities/Pet/Pet.cs
> +        if (string.IsNullOrWhiteSpace(petsName))
Он уже есть. В папке Shared файл ProjectConstants. Она используется часто в конфигурациях. Как ты в уроке показывал.

2024-11-14 09:03 UTC, TikhonovNikita1996 commented on Backend/src/PetFamily.Domain/Entities/Pet/Species.cs
> +    public List<Breed> Breeds { get; set; }
Так сделал, но результат будет в следующем коммите на задачу 4.4. Я начал задание случайно в этой ветке и забыл убрать.

2024-11-14 09:43 UTC, TikhonovNikita1996 commented on Backend/src/PetFamily.Domain/Entities/Volunteer/Volunteer.cs
> +        if (age == 0)
Поправил

2024-11-14 09:45 UTC, KirillSachkov approved these changes

2024-11-14 09:49 UTC, merged